version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.69.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build for production 
          command: "cargo build --release"
      - persist_to_workspace:
          root: .
          paths:
            - target/release/
  store-artifacts:
    docker:
      - image: cimg/base:2023.04
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          mkdir -p /tmp/artifacts/
          find target/release/ -type f -exec cp {} /tmp/artifacts/ \;
      - store_artifacts:
          path: /tmp/artifacts/

